name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
softdepend: [ProtocolLib]
api-version: 1.13
commands:
    bimmlibchat:
        usage: /<command>